name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag testing-image:$(date +%s)

    - name: Run tests inside container
      run: docker run --name test_container ${{github.workspace}}:/app testing-image pytest src/test_app.py
